baseURL = '/'
languageCode = 'zh-Hant-TW'
title = 'Hugo Site Demo - ja-errorpro'
theme = "PaperMod"
timeZone = "Asia/Taipei"

[permalinks]
posts = "/posts/:year/:filename/"

[[menu.main]]
name = "主頁"
url = "/"
weight = 1