name: hugosite

on:
  push:
    branches:
      - main  # 當main分支有push操作時

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true  # 找尋Hugo主題(true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: 'latest' # hugo 版本
          extended: true  # 如果是使用extended版本的務必取消註解。

      - name: Build
        run: git submodule add --force --depth=1 https://github.com/adityatelange/hugo-PaperMod themes/PaperMod && git submodule update --init --recursive && hugo --minify
      
      #- name: Setdomain
      #  run: echo ja-errorpro.codes > ./public/CNAME
      
      
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.HUGO_DEPLOY_TOKEN }}
          PUBLISH_BRANCH: gh-pages  # 推送到 gh-pages 分支
          PUBLISH_DIR: ./public     # hugo 生成的目錄
          commit_message: ${{ github.event.head_commit.message }}